[features]
seeds = false
skip-lint = false

[programs.localnet]
todo_list = "7bfQJKPLfXtzwTN5TxLmoAP6jwEswHDQMPAy3hTBA4F2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/park/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
